**WEEK 1 – DATA SCIENCE WITH PYTHON**

**Project:Analyze Student Marks Dataset**

**Name:** Priya Dharshini R\
**Roll No:** 24BAD092

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("/content/sample_data/StudentsPerformance.csv")

In [4]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [5]:
df.shape

(1000, 8)

In [6]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [8]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [9]:
df = df.dropna()

In [10]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [11]:
print("Average Math Score:", df["math score"].mean())
print("Average Reading Score:", df["reading score"].mean())
print("Average Writing Score:", df["writing score"].mean())

Average Math Score: 66.089
Average Reading Score: 69.169
Average Writing Score: 68.054

In [12]:
print("Maximum Math Score:", df["math score"].max())
print("Maximum Reading Score:", df["reading score"].max())
print("Maximum Writing Score:", df["writing score"].max())

Maximum Math Score: 100
Maximum Reading Score: 100
Maximum Writing Score: 100

In [13]:
print("Minimum Math Score:", df["math score"].min())
print("Minimum Reading Score:", df["reading score"].min())
print("Minimum Writing Score:", df["writing score"].min())

Minimum Math Score: 0
Minimum Reading Score: 17
Minimum Writing Score: 10

In [14]:
score_summary = df[["math score", "reading score", "writing score"]].agg(
    ["mean", "max", "min"]
)

score_summary

      math score  reading score  writing score
mean      66.089         69.169         68.054
max      100.000        100.000        100.000
min        0.000         17.000         10.000

**Conclusion:**

The Student Marks Dataset was successfully analyzed using Python,
Pandas, and NumPy. The dataset was checked for missing values and
basic data cleaning was performed. The average, maximum, and minimum
scores for Mathematics, Reading, and Writing were calculated using
Pandas.